---
- name: Install Apache and Upload my Home page
  hosts: all
  become: yes

  vars:
    source_file: /home/anton/Sports/index.html
    destin_file: /var/www/html

  tasks:  
  - name: Print LINUX version
    debug: var=ansible_os_family

  - block:   # ======= Block for RedHat =======
     - name: install the latest version of Apache for RedHat
       yum: name=httpd state=latest

     - name: copy MySite
       copy: src={{ source_file }} dest={{ destin_file}} mode=0555
       notify: Restart Apache in RedHat

     - name: Start service httpd, if not started
       service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block:    # ================= Block for Debian =======
     - name: install Apache for Debian
       apt: name=apache2 state=latest

     - name: copy MySite
       copy: src={{ source_file }} dest={{ destin_file}} mode=0555
       notify: Restart Apache in Debian

     - name: start Apache2
       service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache in RedHat
    service: name=httpd state=restarted

  - name: Restart Apache in Debian
    service: name=apache2 state=restarted
