---
- name: My Super Puper Playbook for Varibilias
  hosts: all
  become: yes

  vars:
    message1: Privet
    message2: World
    secret  : jgjgjgjgjgjgjgjgjg

  tasks:
  - name: Print Se
    debug:
        var: secret
  - debug:
        msg: "Secretnoe slovo: {{ secret }}"

  - debug:
        msg: "Vladelec Servera -->{{ owner }}<--"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"
  - debug:
      var:full_message
    
    

